import type { Metadata } from 'next';
import './globals.css';
import { SideNavigation } from './client/side-navigation';
import { TopBar } from './client/top-bar';

export const metadata: Metadata = {
  title: 'Auto scroll playground',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="grid h-screen grid-rows-[auto_1fr]">
          <TopBar />
          <main className="bg-background p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
